[package]
name = "fluvio-test"
version = "0.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2021"
autotests = false
description = "Fluvio Test Utility"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"
publish = false

[dependencies]
async-channel = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
futures-lite = { workspace = true }
futures ={ workspace = true }
clap = { workspace = true , features = [   "std",  "derive"]}

rand = { workspace = true }
# Cryptographically secure rand is unnecessary and slow enough to affect for benchmark testing
fastrand = "2.0.0"
md-5 = "0.10"
nix = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true}
serde_yaml = { workspace = true }
inventory = "0.3"
tokio = { workspace = true,  features = ["macros"] }
comfy-table = "7.0.1"
hdrhistogram = "7.3.0"
crc = "3.0"
fork = "0.1"
crossbeam-channel = "0.5"
sysinfo = { workspace = true }
signal-hook = "0.3.13"
indicatif = "0.17.0"
async-std = { workspace = true,  features = ["attributes",] }
uuid = { version = "1.1", features = ["serde", "v4"] }

tracing = { workspace = true }

# Fluvio dependencies
fluvio = { workspace = true}
fluvio-types = { workspace = true  }
fluvio-future = { workspace = true, features = [
    "io",
    "task",
    "timer",
    "subscriber",
    "fixture",
] }
fluvio-command = { version = "0.2.0" }
fluvio-cluster = { path = "../fluvio-cluster" }
fluvio-cli = { path = "../fluvio-cli" }
fluvio-controlplane-metadata = { workspace = true, features = ["k8"]}

# Fluvio test framework Attribute macro
fluvio-test-derive = { path = "../fluvio-test-derive" }
fluvio-test-util = { path = "../fluvio-test-util" }
fluvio-protocol = { workspace = true,  features = ["api"] }

# Fluvio test framework Options derive
fluvio-test-case-derive = { path = "../fluvio-test-case-derive" }
