[package]
name = "fluvio-test"
version = "0.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2018"
autotests = false
description = "Fluvio Test Utility"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"
publish = false

[dependencies]
tracing = "0.1"
bytes = "1.0"
futures-lite = "1.11.0"
futures = "0.3"
structopt = "0.3.5"
async-trait = "0.1.21"
syn = { version = "1.0", features = ["full"]}
rand = "0.8"
md-5 = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_bytes = "0.11.5"
inventory = "0.1"
tokio = { version = "1.4", features = ["macros"] }
bencher = "0.1"
prettytable-rs = "0.8"
#hdrhistogram = "7.3.0"
crc = "2.0"
fork = "0.1"
nix = "0.22"

# Fluvio dependencies
fluvio = { path = "../fluvio" }
fluvio-types = { version = "0.2.0", path = "../fluvio-types" }
fluvio-future = { version = "0.3.0", features = ["task", "timer", "subscriber", "fixture"] }
fluvio-command = { version = "0.2.0" }
fluvio-cluster = { path = "../fluvio-cluster" }
fluvio-controlplane-metadata = { features = ["k8"], path = "../fluvio-controlplane-metadata" }
dataplane = { path = "../fluvio-dataplane-protocol", package = "fluvio-dataplane-protocol" }

# Fluvio test framework Attribute macro
fluvio-test-derive = { path = "../fluvio-test-derive" }
fluvio-test-util = { path = "../fluvio-test-util" }