[package]
name = "fluvio-protocol-codec"
edition = "2018"
version = "0.3.2"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Frame encoder and decoder for fluvio protocol"
repository = "https://github.com/infinyon/fluvio-protocol"
license = "Apache-2.0"
categories = ["encoding","api-bindings"]

[dependencies]
log = "0.4.8"
bytes = "1.0.0"
tokio-util = { version = "0.6.4", features = ["codec","compat"]}
fluvio-protocol = { version = "0.3.1", path = "../fluvio-protocol-core", package = "fluvio-protocol-core" }

[dev-dependencies]
fluvio-future = { version = "0.3.0", features = ["fixture","timer","net"] }
futures = { version = "0.3.1" }
flv-util = { version = "0.5.0"}
