[package]
name = "flv-node-client"
version = "1.0.1"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]
license = "Apache-2.0"
repository = "https://github.com/infinyon/fluvio"
description = "Node JS Client for Fluvio"
readme = "REAMD.md"

[lib]
crate-type = ["cdylib"]
test = false

[dependencies]
log = "0.4.8"
futures = { version = "0.3.4", features = ['async-await'] }
flv-future-aio = { version = "2.0.0" }
node-bindgen = { version = "1.0.0" }
kf-protocol = { version = "1.1.0", path = "../kf-protocol"}
types = { path = "../types", package = "flv-types"}
flv-client = { version = "2.0.0", path = "../client-rs"}


