[package]
name = "fluvio-runner"
version = "0.4.0"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio Engine Runner"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"
publish = false

[lib]
name = "fluvio_runner"
path = "src/lib.rs"

[[bin]]
name = "fluvio-run"
path = "src/bin/main.rs"
doc = false

[dependencies]
structopt = { version = "0.3.16", default-features = false }
thiserror = "1.0.20"
semver = "0.11.0"
serde_json = "1.0.64"

# regardless of TLS, sc and spu always use openssl_tls for now because we need cert API
fluvio-future = { version = "0.2.0", features = ["subscriber"] }
fluvio-sc = { version = "0.6.0", path = "../sc" }
fluvio-spu = { version = "0.5.0", path = "../spu" }
fluvio-extension-common = { version = "0.3.0", path = "../extension-common" }
