[package]
name = "regex"
group = "infinyon"
version = "0.1.0"
apiVersion = "0.1.0"
description = "Regex SmartModule"
license = "Apache-2.0"
repository = "https://github.com/infinyon/fluvio"

[params]
regex = { description = "Regex filter" }


