[package]
name = "fluvio-sc"
edition = "2018"
version = "0.1.0"
authors = ["fluvio.io"]

[lib]
name = "fluvio_sc"
path = "src/lib.rs"

[[bin]]
name = "fluvio-sc-k8"
path = "src/bin/k8.rs"

[features]
default = []
k8 = ["k8-client"]

[dependencies]
rand = "0.7.2"
log = "0.4.0"
tracing = "0.1.19"
tracing-futures = "0.2.4"
toml = "0.5.5"
serde = { version = "1.0.103", features = ['derive'] }
futures-util = { version = "0.3.5" }
chashmap = "2.2.0"
base64 = "0.11.0"
regex = "1.3.1"
async-trait = "0.1.21"
async-lock = "1.1.2"
async-channel = "1.4.0"
event-listener = "2.2.0"
tokio = { version = "0.2.21", features = ["macros"] }
structopt = "0.3.17"

# Fluvio dependencies
fluvio-future = { version = "0.1.0", features = ["tls","subscriber"] }
fluvio-types = { path = "../types", version = "0.1.0" }
fluvio-sc-schema = { version = "0.1.0", path = "../sc-schema" }
fluvio-controlplane = { version = "0.1.0", path = "../controlplane" }
fluvio-controlplane-metadata = { version = "0.1.0", features = ["k8"], path = "../controlplane-metadata" }
fluvio-stream-dispatcher = { version = "0.1.0", path = "../stream-dispatcher" }
k8-client = { version = "2.1.0", optional = true }
k8-metadata-client = { version = "1.0.2" }
k8-obj-metadata = { version = "1.0.0" }
fluvio-protocol = { version = "0.2.0" }
dataplane = { version = "0.1.0", path = "../dataplane-protocol", package = "fluvio-dataplane-protocol" }
fluvio-socket = { version = "0.1.0" }
fluvio-service = { version = "0.1.0" }
flv-tls-proxy = "0.2.0"
utils = { version = "0.1.0", path = "../utils", package = "fluvio-system-util" }

[dev-dependencies]
fluvio-future = { version = "0.1.0", features = ["fixture"] }
flv-util = { version = "0.5.0", features = ["fixture"] }
