[package]
name = "flv-eventstream-model"
edition = "2018"
version = "0.1.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio Event Stream Model"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"

[lib]
name = "flv_eventstream_model"
path = "src/lib.rs"

[features]
use_serde = ["serde"]
k8 = ["use_serde", "k8-obj-metadata", "k8-obj-core", "k8-obj-app"]

[dependencies]
tracing = "0.1.19"
serde = { version = "1.0.0", features = ['derive'], optional = true }

# Fluvio dependencies
flv-util = { version = "0.2.0" }
flv-types = { path = "../types", version = "0.2.0" }
flv-future-aio = { version = "2.3.0" }
k8-obj-app = { version = "1.1.0", optional = true }
k8-obj-core = { version = "1.1.0", optional = true }
k8-obj-metadata = { version = "1.0.0", optional = true }

[dev-dependencies]
flv-future-aio = { version = "2.3.0", features = ["fixture"] }