[package]
name = "fluvio-smartmodule-package"
version = "0.0.0"
edition = "2021"
publish =  false
license = "Apache-2.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
categories = ["wasm"]
keywords = ["streaming", "stream", "wasm", "fluvio","hub"]
repository = "https://github.com/infinyon/fluvio"
description = "Fluvio SmartModule Package"


[lib]
crate-type = ['lib']