[package]
name = "fluvio-smartmodule-filter-hashset"
version = "0.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2024"
publish = false

[lib]
crate-type = ['cdylib', 'rlib']

[dependencies]
fluvio-smartmodule = { workspace = true }
