[package]
name = "flv-tls-proxy"
version = "0.1.0"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Simple Local Proxy"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"
categories = ["encoding"]


[dependencies]
log = "0.4.8"
futures = { version = "0.3.4" }
flv-future-aio = { version = "2.0.0", features = ["tls"] }
async-std = { version = "1.5.0", features = ["default","unstable"] }