[package]
name = "flv-eventstream-dispatcher"
edition = "2018"
version = "0.1.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio Event Stream Stroe access"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"

[lib]
name = "flv_eventstream_dispatcher"
path = "src/lib.rs"

[dependencies]
log = "0.4.8"
tracing = "0.1.19"
tracing-futures = "0.2.4"
serde = { version = "1.0.103", features = ['derive'] }
futures = { version = "0.3.1" }
async-trait = "0.1.21"
async-lock = "1.1.2"
async-channel = "1.1.0"
event-listener = "2.2.0"
tokio = { version = "0.2.21", features = ["macros"] }

# Fluvio dependencies
flv-util = { version = "0.2.0" }
flv-types = { path = "../types", version = "0.2.0" }
flv-future-aio = { version = "2.3.0", features = ["unstable"] }
flv-eventstream-model = { features = ["k8"], path = "../event-stream-model" }
k8-metadata-client = { version = "1.0.1" }

[dev-dependencies]
flv-util = { version = "0.2.0", features = ["fixture"] }
flv-future-aio = { version = "2.3.0", features = ["fixture"] }
