apiVersion: v1
kind: Pod
metadata:
  name: flv-sc
  labels:
    app: flv-sc
spec:
  serviceAccountName: {{ .Values.serviceAccount.name }}
  containers:
    - name: flv-sc
      image: {{ .Values.image.registry }}/fluvio:{{ .Values.image.tag | default .Chart.Version }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - containerPort: 9003
      env:
        - name: RUST_LOG
          value: {{ .Values.scLog }}
        - name:  SPU_IMAGE
          value: {{ .Values.image.registry }}/fluvio:{{ .Values.image.tag | default .Chart.Version }}
      command: ["/fluvio", "run", "sc"]
  {{ if .Values.tls }}
      args:
        - --tls
        - --enable-client-cert
        - --ca-cert
        - /var/certs/ca/ca.crt
        - --server-cert
        - /var/certs/tls/tls.crt
        - --server-key
        - /var/certs/tls/tls.key
        - --bind-non-tls-public
        - 0.0.0.0:9005
        {{ if .Values.authorizationConfigMap }}
        - --authorization-policy
        - /etc/fluvio-authorization/policy
        - --authorization-scopes
        - /etc/fluvio-authorization/scopes
        {{ end }}
      volumeMounts:
        - name: cacert
          mountPath: /var/certs/ca  
          readOnly: true
        - name: tls
          mountPath: /var/certs/tls
        {{ if .Values.authorizationConfigMap }}
        - name: authorization-config
          mountPath: /etc/fluvio-authorization
        {{ end }}
  volumes:
    - name: cacert
      secret:
        secretName: {{ .Values.cert.caCert }}
    - name: tls
      secret:
        secretName: {{ .Values.cert.tls }}
    {{ if .Values.authorizationConfigMap }}
    - name: authorization-config
      configMap:
        name: {{ .Values.authorizationConfigMap }}
        items:
        - key: POLICY
          path: policy
        - key: SCOPES
          path: scopes
    {{ end }}
  {{ end }}