[package]
name = "fluvio-stream-model"
edition = "2018"
version = "0.3.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio Event Stream Model"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"

[lib]
name = "fluvio_stream_model"
path = "src/lib.rs"

[features]
use_serde = ["serde"]
k8 = ["use_serde", "k8-obj-app"]

[dependencies]
tracing = "0.1.19"
serde = { version = "1.0.0", features = ['derive'], optional = true }
async-rwlock = "1.3.0"
event-listener = "2.5.1"

# Fluvio dependencies
k8-obj-app = { version = "2.0.0", optional = true }


[dev-dependencies]
tokio = { version = "0.2.21", features = ["macros"] }
fluvio-future = { version = "0.1.0", features = ["fixture"] }
