[package]
name = "fluvio-wasm-map-regex"
version = "0.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2021"
publish =  false

[lib]
crate-type = ['cdylib']

[dependencies]
fluvio-smartmodule = { path = "../../", version = "0.1.0" }
regex = "1"
once_cell = "1"
