[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"

[lib]
crate-type = ['cdylib']

[dependencies]
fluvio-smartmodule = { {{smartmodule-version}} }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
{% if smartmodule-init %}{% if smartmodule-type == "filter" %}once_cell = "1.13.0"{% endif %}{% endif %}

[profile.release-lto]
inherits = "release"
lto = true
