[package]
name = "fluvio-spu"
edition = "2021"
version = "0.0.0"
authors = ["fluvio.io"]
description = "Fluvio Stream Processing Unit"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"
publish = false

[lib]
name = "fluvio_spu"
path = "src/lib.rs"

[[bin]]
name = "fluvio-spu"
path = "src/main.rs"
doc = false

[features]
default = ["smartengine"]
smartengine = ["dep:fluvio-smartengine", "fluvio/smartengine"]

[dependencies]
cfg-if = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true, features = ["std", "derive", "env"]}
thiserror = { workspace = true }
futures-util = { workspace = true, features = ["sink"] }
async-trait = { workspace = true }
serde = { workspace = true,  features = ['derive'] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
async-channel = { workspace = true }
async-lock = { workspace = true }
async-io = { workspace = true }
adaptive_backoff = { workspace = true }
once_cell = { workspace = true }
sysinfo = { workspace = true }
chrono = { workspace = true }
mimalloc = { workspace = true }

# Fluvio dependencies
fluvio = { workspace = true }
fluvio-auth = { workspace = true }
fluvio-types = { workspace = true, features = ["events"] }
fluvio-storage = { workspace = true, features = ["iterators"] }
fluvio-compression = { workspace = true }
fluvio-controlplane = { workspace = true }
fluvio-controlplane-metadata = { workspace = true }
fluvio-spu-schema = { workspace = true,  features = ["file"] }
fluvio-protocol = { workspace = true }
fluvio-socket = { workspace = true, features = ["file",] }
fluvio-service = { workspace = true }
flv-tls-proxy = { workspace = true }
flv-util = { workspace = true }
fluvio-future = { workspace = true,features = [
    "subscriber",
    "openssl_tls",
    "zero_copy",
] }
fluvio-smartengine = { workspace = true, optional = true, features = ["engine"] }
fluvio-smartmodule = { workspace = true}
fluvio-kv-storage = { workspace = true}

[dev-dependencies]
once_cell = { workspace = true }
derive_builder =  { workspace = true }
serde_json = { workspace = true }
flate2 = { workspace = true }
portpicker = { workspace = true }

flv-util = { workspace = true, features = ["fixture"] }
fluvio-future = { workspace = true,features = ["fixture", "subscriber"] }
fluvio-protocol = { workspace = true,  features = ["fixture"] }
