[package]
name = "fluvio-spu"
edition = "2021"
version = "0.0.0"
authors = ["fluvio.io"]
description = "Fluvio Stream Processing Unit"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"
publish = false

[lib]
name = "fluvio_spu"
path = "src/lib.rs"

[[bin]]
name = "fluvio-spu"
path = "src/main.rs"
doc = false

[dependencies]
cfg-if = "1.0.0"
anyhow = { workspace = true }
tracing = "0.1.27"
bytes = "1.0.0"
clap = { version = "4.0.15", features = ["std", "derive", "env"], default-features = false }
toml = "0.5.5"
futures-util = { version = "0.3.5", features = ["sink"] }
async-trait = "0.1.51"
serde = { version = "1.0.103", features = ['derive'] }
pin-utils = "0.1.0-alpha.4"
regex = "1.3.1"
tokio = { version = "1.3.0", features = ["macros"] }
async-channel = "1.5.1"
async-rwlock = "1.1.0"
async-lock = "2.4.0"
event-listener = "2.4.0"
async-io = "1.3.1"
adaptive_backoff = "0.2.1"
thiserror = "1"
once_cell = "1.5"
sysinfo = "0.26.0"
nix = { version = "0.25"}


# Fluvio dependencies
fluvio = { path = "../fluvio" }
fluvio-types = { features = [
    "events",
], path = "../fluvio-types" }
fluvio-storage = { path = "../fluvio-storage" }
fluvio-compression = { path = "../fluvio-compression" }
fluvio-controlplane = { path = "../fluvio-controlplane" }
fluvio-controlplane-metadata = { path = "../fluvio-controlplane-metadata" }
fluvio-spu-schema = { path = "../fluvio-spu-schema", features = [
    "file",
] }
fluvio-protocol = { path = "../fluvio-protocol" }
fluvio-socket = { path = "../fluvio-socket", features = [
    "file",
] }
fluvio-service = { path = "../fluvio-service" }
flv-tls-proxy = { version = "0.6.0" }
flv-util = { version = "0.5.0" }
fluvio-future = { version = "0.4.0", features = [
    "subscriber",
    "openssl_tls",
    "zero_copy",
] }
fluvio-smartengine = { path = "../fluvio-smartengine" }
fluvio-smartmodule = { path = "../fluvio-smartmodule",  default-features = false }

[dev-dependencies]
once_cell = "1.5.2"
derive_builder = { version = "0.11.0" }
serde_json = "1"
flate2 = "1.0.22"
portpicker = "0.1.1"

flv-util = { version = "0.5.2", features = ["fixture"] }
fluvio-future = { version = "0.4.0", features = ["fixture", "subscriber"] }
fluvio-protocol = { path = "../fluvio-protocol", features = ["fixture"] }

