version = "1.0"
current_profile = "local"

[profile.local3]
cluster = "local"
topic = "test3"
partition = 3

[profile.local]
cluster = "local"

[profile.local2]
cluster = "local"
topic = "test3"

[cluster.extra]
endpoint = "127.0.0.1:9003"
use_spu_local_address = false

[cluster.extra.tls]
tls_policy = "disabled"

[cluster.extra.metadata.deep.nesting.example]
key = "custom field"

[cluster.extra.metadata.installation]
type = "local"

[cluster.local]
endpoint = "127.0.0.1:9003"
use_spu_local_address = false

[cluster.local.tls]
tls_policy = "disabled"

[cluster.ec2]
endpoint = "sandbox.xxxx.eksctl.io:9003"
use_spu_local_address = false

[cluster.ec2.tls]
tls_policy = "disabled"
