[package]
name = "async-test-derive"
version = "0.2.1"
edition = "2018"
authors = ["fluvio.io"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0.2"
syn = { version = "1.0.14", features = ["full"] }
log = "0.4.8"
