[workspace]
members = [
    "aggregate",
    "aggregate-sum",
    "aggregate-json",
    "aggregate-average",
    "filter",
    "filter_odd",
    "filter_json",
    "filter_regex",
    "map",
    "map_double",
    "map_json",
    "map_regex",
    "flatmap_json",
]

# lto is need to reduce wasm binary size
[profile.release]
lto = true