[package]
name = "flv-api-spu"
version = "2.0.0"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio API for SPU"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"

[dependencies]
log = "0.4.8"
bytes = "0.5.4"
serde = { version ="1.0.103", features = ['derive'] }
kf-protocol = { version = "2.0.1" } 
