[package]
name = "kf-protocol-transport"
edition = "2018"
version = "2.0.1"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Transport frame encoder and decoder for Kakfa protocol"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"
categories = ["encoding","api-bindings"]

[dependencies]
log = "0.4.8"
bytes = "0.5.3"
tokio-util = { version = "0.3.1", features = ["codec","compat"]}
flv-future-aio = { version = "2.1.0" }
kf-protocol = { version = "0.1.0", path = "../kf-protocol-core", package = "kf-protocol-core" }

[dev-dependencies]
flv-future-aio = { version = "2.1.0", features = ["fixture"] }
futures = { version = "0.3.1" }
flv-util = { version = "0.1.0"}