[package]
name = "echo"
version = "0.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2024"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { workspace = true }
async-std = { workspace = true, features = ["attributes"] }
anyhow = { workspace = true }

fluvio = { workspace = true  }
