[package]
name = "k8-fixtures"
edition = "2018"
version = "0.2.1"
authors = ["fluvio.io"]

[dependencies]
rand = "0.7.2"
serde = "1.0.76"
serde_derive = "1.0.76"
serde_json = "1.0.27"
k8-client = { path = "../../k8-client"}
k8-metadata = { path = "../../k8-metadata"}

