[package]
name = "fluvio-cluster"
version = "0.5.2"
edition = "2018"
license = "Apache-2.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
repository = "https://github.com/infinyon/fluvio"
description = "Tools for installing and managing Fluvio clusters"

[lib]
name = "fluvio_cluster"
path = "src/lib.rs"

[[bin]]
name = "fluvio-cluster"
path = "src/main.rs"
required-features = ["cli"]

[features]
cli = [
    "structopt",
    "color-eyre",
    "prettytable-rs",
    "fluvio-runner-local/platform",
    "fluvio-extension-common/target",
]
platform = []

[dependencies]
colored = "2.0.0"
semver = "0.10.0"
url = "2.1.1"
tracing = "0.1.19"
tracing-futures = "0.2.4"
serde = "1.0.115"
serde_json = "1.0.57"
thiserror = "1.0.20"
async-trait = "0.1.21"
color-eyre = { version = "0.5.8", default-features = false, optional = true }
structopt = { version = "0.3.16", default-features = false, optional = true }
prettytable-rs = { version = "0.8.0", optional = true }
async-channel = "1.5.1"
futures-lite = "1.11.0"
tokio = { version = "0.2.21", features = ["macros"] }
once_cell = "1.5"

# Fluvio dependencies
fluvio = { version = "0.3.0", path = "../client", default-features = false }
fluvio-helm = "0.1.0"
fluvio-future = { version = "0.1.13" }
fluvio-runner-local = { version = "0.2.0", path = "../extension-runner-local", optional = true }
fluvio-extension-common = { version = "0.1.0", path = "../extension-common", optional = true }
fluvio-controlplane-metadata = { version = "0.3.0", path = "../controlplane-metadata", features = ["k8"] }
flv-util = "0.5.2"
k8-config = { version = "1.3.0" }
k8-client = { version = "4.0.0" }
k8-metadata-client = { version = "2.0.0" }

[dev-dependencies]
fluvio-future = { version = "0.1.0", features = ["task"] }
