[package]
name = "fluvio-cluster"
version = "0.1.2"
edition = "2018"
license = "Apache-2.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
repository = "https://github.com/infinyon/fluvio"
description = "Tools for installing and managing Fluvio clusters"


[lib]
name = "fluvio_cluster"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
semver = "0.10.0"
url = "2.1.1"
tracing = "0.1.19"
tracing-futures = "0.2.4"
serde = "1.0.115"
serde_json = "1.0.57"
thiserror = "1.0.20"

# Fluvio dependencies
fluvio = { version = "0.2.0", path = "../client" }
fluvio-controlplane-metadata = { version = "0.1.0", path = "../controlplane-metadata", features = ["k8"] }
fluvio-future = { version = "0.1.0" }
flv-util = "0.5.2"
k8-config = { version = "1.3.0", features = ["context"] }
k8-client = "2.1.0"
k8-obj-core = "1.1.0"
k8-obj-metadata = "1.0.0"

[dev-dependencies]
fluvio-future = { version = "0.1.0", features =["task"]}