[package]
name = "fluvio-smartstream"
version = "0.2.3"
edition = "2018"
license = "Apache-2.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
categories = ["wasm", "database", "encoding"]
keywords = ["streaming", "stream", "wasm", "fluvio"]
repository = "https://github.com/infinyon/fluvio"
description = "Fluvio SmartStream WASM library"

[features]
default = ["derive"]
derive = ["fluvio-smartstream-derive"]

[lib]
crate-type = ['lib']

[dependencies]
eyre = { version = "0.6", default-features = false }
fluvio-dataplane-protocol = { version = "0.7.3", path = "../fluvio-dataplane-protocol", default-features = false }
fluvio-smartstream-derive = { version = "0.1.1", path = "../fluvio-smartstream-derive", optional = true }
