[package]
name = "flv-metadata"
edition = "2018"
version = "2.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio metadata"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"

[features]
use_serde = ["serde"]
k8 = ["use_serde","k8-obj-metadata","k8-obj-core","k8-obj-app","flv-eventstream-model/k8"]

[dependencies]
log = "0.4.8"
serde = { version ="1.0.0", features = ['derive'], optional = true }
async-trait = "0.1.21"
k8-obj-metadata = { version = "1.0.0", optional = true }
k8-obj-core = { version = "1.1.0", optional = true}
k8-obj-app = { version = "1.1.0", optional = true }
flv-future-aio = { version = "2.3.0"}
kf-protocol =  "2.0.0" 
flv-types = { path ="../types", version = "0.2.0" }
flv-util = { version = "0.2.0"}
flv-eventstream-model = { path = "../event-stream-model"}

[dev-dependencies]
flv-future-aio = { version = "2.3.0", features=["fixture"]}