[package]
name = "fluvio-dataplane-protocol"
version = "0.1.0"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "data plane protocol"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"
categories = ["encoding", "api-bindings"]


[dependencies]
log = "0.4.0"
bytes = "0.5.3"
futures = { version = "0.3.4" }
content_inspector = "0.2.4"
crc32c = { version = "0.5" }
fluvio-future = { version = "0.1.0" }
fluvio-protocol = { version = "0.2.0", features = ["derive", "api", "store"] }
flv-util = { version = "0.5.0" }

[dev-dependencies]
kf-socket = { version = "3.0.0", path = "../kf-socket" }
