[package]
name = "produce"
version = "0.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2024"
publish = false

[dependencies]
async-std = { workspace = true,  features = ["attributes"] }
anyhow = { workspace = true }

fluvio = { workspace = true  }