version: 0.1.0
name: my-test-mqtt
type: mqtt
topic: my-mqtt
create_topic: false
direction: source
parameters:
  param_1: "mqtt.hsl.fi"
  param_2:
    foo: bar
    bar: foo
  param_3:
    - "baz"
secrets:
  foo: bar
producer:
  linger: 1ms
  batch_size: '44 MB'
  compression: gzip
consumer:
  partition: 10
