[package]
name = "k8-dderive"
version = "0.2.1"
edition = "2018"
authors = ["fluvio.io"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.24"
quote = "0.6.10"
syn = "0.15.21"
log = "0.4.8"
