[package]
name = "fluvio-types"
version = "0.2.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2018"
description = "Fluvio common types"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"

[dependencies]
tracing = "0.1.19"
