[package]
name = "fluvio-smartmodule-aggregate-with-timestamp"
version = "0.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2024"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
chrono = { version = "0.4.26", default-features = false }

# Fluvio
fluvio-smartmodule = { workspace = true }
