[package]
name = "fluvio-cluster"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
repository = "https://github.com/infinyon/fluvio"
description = "Tools for installing and managing Fluvio clusters"

[lib]
name = "fluvio_cluster"
path = "src/lib.rs"

[features]
cli = [
    "clap",
    "color-eyre",
    "duct",
    "comfy-table",
    "tar",
    "flate2",
    "fluvio-extension-common/target",
    "fluvio-sc-schema/use_serde",
]

[dependencies]
colored = "2.0.0"
semver = "1.0.3"
url = "2.1.1"
tracing = "0.1.19"
serde = "1.0.115"
serde_json = "1.0.57"
serde_yaml = "0.9.0"
thiserror = "1.0.20"
async-trait = "0.1.21"
futures-util = "0.3"
futures-channel = { version = "0.3", features = ["sink"] }
tokio = { version = "1.3.0", features = ["macros"] }
once_cell = "1.5"
derive_builder = "0.11.0"
which = "4.1.0"
directories = "4.0.0"
tempfile = "3.2"
include_dir = "0.7.2"
tempdir = "0.3.7"
anyhow = "1.0.44"
async-channel = "1.6.1"
indicatif = "0.17.0"
rand = "0.8.4"
chrono = { version = "0.4" }
color-eyre = { version = "0.6.0", default-features = false, optional = true }
clap = { version = "4.0.8", features = [
    "std",
    "derive",
], default-features = false, optional = true }
duct = { version = "0.13", default-features = false, optional = true }
comfy-table = { version = "6.0.0", default-features = false, optional = true }
flate2 = { version = "1", default-features = false, optional = true }
tar = { version = "0.4", default-features = false, optional = true }
sysinfo = { version = "0.26.0", default-features = false}
portpicker = "0.1.1"

# External Fluvio dependencies
fluvio-helm = "0.4.1"
flv-util = "0.5.2"
k8-config = { version = "2.0.0" }
k8-client = { version = "7.0.0" }
k8-metadata-client = { version = "4.0.0" }
k8-types = { version = "0.6.0", features = ["app"] }
fluvio-command = { version = "0.2.0" }
fluvio-future = { version = "0.4.0" }

fluvio = { path = "../fluvio", default-features = false }
fluvio-extension-common = { path = "../fluvio-extension-common", optional = true }
fluvio-controlplane-metadata = { path = "../fluvio-controlplane-metadata", features = [
    "k8",
] }
fluvio-sc-schema = { path = "../fluvio-sc-schema", default-features = false }
fluvio-types = { path = "../fluvio-types" }
fluvio-channel = { path = "../fluvio-channel" }

[dev-dependencies]
fluvio-future = { version = "0.4.0", features = ["task", "fixture"] }
