[package]
name = "fluvio-controlplane"
version = "0.7.1"
edition = "2018"
license = "Apache-2.0"
description = "Fluvio control plane API"
authors = ["fluvio.io"]
repository = "https://github.com/infinyon/fluvio"

[lib]
name = "fluvio_controlplane"
path = "src/lib.rs"

[dependencies]
log = "0.4.8"
tracing = "0.1.19"
bytes = "1"

# Fluvio dependencies
fluvio-types = { path = "../types", version = "0.2.0" }
fluvio-controlplane-metadata = { path = "../controlplane-metadata", version = "0.9.1" }
fluvio-protocol = { path = "../protocol", version = "0.6" }
dataplane = { version = "0.6", path = "../dataplane-protocol", package = "fluvio-dataplane-protocol" }
