[package]
name = "fluvio-controlplane"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
authors = ["fluvio.io"]
repository = "https://github.com/infinyon/fluvio"

[lib]
name = "fluvio_controlplane"
path = "src/lib.rs"

[dependencies]
log = "0.4.8"
tracing = "0.1.19"

# Fluvio dependencies
fluvio-types = { path ="../types" }
fluvio-controlplane-metadata = { path = "../controlplane-metadata"}
fluvio-protocol = { version = "0.1.0", git = 'https://github.com/infinyon/fluvio-protocol.git', branch = 'fluvio_only', features = ["derive", "api"] }
dataplane-protocol = { version = "0.1.0", path = "../dataplane-protocol"}

