[package]
name = "utils"
version = "0.3.0"
authors = ["fluvio.io"]
edition = "2018"

[features]
default = []
fixture = []

[dependencies]
tracing = "0.1.19"
regex = "1.3.1"
rand = "0.7.2"

# Fluvio dependencies
flv-types = { path = "../types", version = "0.2.0" }
