[package]
name = "fluvio-socket"
version = "0.14.1"
edition = "2021"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Provide TCP socket wrapper for fluvio protocol"
repository = "https://github.com/infinyon/fluvio-socket"
license = "Apache-2.0"
categories = ["encoding"]

[lib]
name = "fluvio_socket"
path = "src/lib.rs"

[features]
file = ["fluvio-future/zero_copy", "fluvio-protocol/store"]

[dependencies]
tracing = { workspace = true }
cfg-if = { workspace = true }
bytes = { workspace = true }
once_cell = { workspace = true }
futures-util = { version = "0.3.5", features = ["sink", "io"] }
async-lock = "2.4.0"
event-listener = "2.0.0"
async-channel = "1.6.1"
tokio = { workspace = true, features = ["macros"] }
tokio-util = { version = "0.7.0", features = ["codec", "compat"] }
async-trait = { workspace = true }
pin-project = "1.0.1"
thiserror = { workspace = true }
semver = "1.0.0"

# Fluvio dependencies
fluvio-future = { workspace = true, features = ["net", "task", "retry"] }
fluvio-protocol = { path = "../fluvio-protocol", version = "0.9", features = [
    "derive",
    "api",
    "codec",
    "link",
] }

[dev-dependencies]
fluvio-future = { workspace = true, features = [
    "fixture",
    "fs",
    "zero_copy",
    "native2_tls",
] }
portpicker = "0.1.1"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
async-net = "1.4.3"

[build-dependencies]
built = "0.6.0"
