[package]
name = "fluvio-connector-manager"
version = "0.0.0"
edition = "2018"
publish = false
description = "The fluvio connectors management tool."


[dependencies]
structopt = "0.3"
thiserror = "1.0.25"
tracing = "0.1.19"
serde = { version = "1.0.115", features = ["derive"] }
serde_yaml = "0.8.17"
prettytable-rs = { version = "0.8.0" }

fluvio = { path = "../fluvio/", version = "0.9.2" }
fluvio-extension-common = { path = "../fluvio-extension-common/" }
fluvio-controlplane-metadata = { path = "../fluvio-controlplane-metadata/", features = ["k8", "use_serde"] }
fluvio-future = { version ="0.3.8", features = ["subscriber"] }
