[package]
name = "fluvio-stream-dispatcher"
edition = "2021"
version = "0.11.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio Event Stream access"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"

[lib]
name = "fluvio_stream_dispatcher"
path = "src/lib.rs"

[dependencies]

async-trait = { workspace = true }
async-lock = { workspace = true }
async-channel = { workspace = true }
event-listener = { workspace = true }
futures-lite = { workspace = true }
futures-util = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true,  features = ['derive'] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }

# Fluvio dependencies
fluvio-types = { workspace = true }
fluvio-stream-model = { workspace = true, features = [ "k8"]  }
k8-diff = { workspace = true }
k8-metadata-client = { workspace = true }
k8-types = { workspace = true }
fluvio-future = { workspace = true, features = ["task", "timer"] }

[dev-dependencies]
fluvio-future = { workspace = true, features = ["fixture"] }
