[package]
name = "fluvio-stream-dispatcher"
edition = "2021"
version = "0.9.3"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio Event Stream access"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"

[lib]
name = "fluvio_stream_dispatcher"
path = "src/lib.rs"

[dependencies]
tracing = "0.1.0"
serde = { version = "1.0.103", features = ['derive'] }
serde_json = "1.0.60"
futures-lite = "1.11.0"
async-trait = "0.1.21"
async-rwlock = "1.3.0"
async-channel = "1.1.0"
event-listener = "2.5.1"
tokio = { version = "1.3.0", features = ["macros"] }
once_cell = "1.5"

# Fluvio dependencies
fluvio-types = { path = "../fluvio-types", version = "0.4.0" }
fluvio-stream-model = { features = [
    "k8",
], version = "0.8.0", path = "../fluvio-stream-model" }
k8-metadata-client = { version = "5.0.0" }
k8-types = { version = "0.7.0" }
fluvio-future = { version = "0.4.0", features = ["task", "timer"] }

[dev-dependencies]
fluvio-future = { version = "0.4.0", features = ["fixture"] }
