[package]
name = "flv-api-sc"
version = "1.2.0"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio API for SC"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"


[dependencies]
log = "0.4.8"
serde = { version ="1.0.103", features = ['derive'] }
kf-protocol = { version = "1.1.3" } 
flv-metadata = { version = "1.0.0",path = "../metadata"}
flv-types = { version = "0.2.0", path ="../types" }
k8-flv-metadata = { version = "1.0.0",path = "../k8-metadata"}
flv-util = { version = "0.2.0"}