apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition 
metadata:
  name: tables.fluvio.infinyon.com
spec:
  group: fluvio.infinyon.com
  scope: Namespaced
  names:
    kind: Table
    plural: tables
    singular: table
  versions:
    - name: v1
      served: true
      storage:  true
      subresources:
          status: {}
      schema:
        openAPIV3Schema:
          required: ["spec"]
          type: object
          properties:
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              required: ["name"]
              properties:
                name:
                  type: string
                  minimum: 1
                  maximum: 100
                input_format:
                  type: string
                  enum:
                    - JSON
                    - YAML
                    - TOML
                column:
                  type: array
                  items:
                    type: object
                    properties:
                      label:
                        type: string
                      width:
                        type: integer 
                      alignment:
                        type: string
                        enum:
                          - LEFT
                          - CENTER
                          - RIGHT
                      path:
                        type: string
                      format:
                        type: string
                smartmodule:
                  type: string