apiVersion: v1
kind: Pod
metadata:
  name: flv-sc
  labels:
    app: flv-sc
spec:
  containers:
    - name: flv-sc
      image: {{ .Values.registry }}/fluvio-sc:{{ .Values.fluvioVersion }}
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9003
      env:
        - name: RUST_LOG
          value: {{ .Values.scLog }}
        - name:  SPU_IMAGE
          value: {{ .Values.registry }}/fluvio-spu:{{ .Values.fluvioVersion }}
