[package]
name = "fluvio-wasm-filter-regex"
version = "0.1.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2018"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
fluvio-smartmodule = { path = "../../", version = "0.4.0" }
regex = "1"
