[package]
name = "fluvio-stream-model"
edition = "2021"
version = "0.9.3"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio Event Stream Model"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"

[lib]
name = "fluvio_stream_model"
path = "src/lib.rs"

[features]
use_serde = ["serde"]
k8 = ["use_serde", "k8-types"]
fixture = []

[dependencies]
async-rwlock = { workspace = true }
event-listener = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true, features = ['derive'], optional = true }
tracing = { workspace = true }

# Fluvio dependencies
k8-types = { workspace = true, optional = true }

[dev-dependencies]
async-std = { workspace = true, features = ["attributes"] }
tokio = { workspace = true, features = ["macros"] }
fluvio-future = { workspace = true, features = ["fixture"] }
