[package]
name = "fluvio-stream-model"
edition = "2021"
version = "0.8.4"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio Event Stream Model"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"

[lib]
name = "fluvio_stream_model"
path = "src/lib.rs"

[features]
use_serde = ["serde"]
k8 = ["use_serde", "k8-types"]
fixture = []

[dependencies]
tracing = "0.1.19"
serde = { version = "1.0.0", features = ['derive'], optional = true }
async-rwlock = "1.3.0"
event-listener = "2.5.1"
once_cell = "1.5"

# Fluvio dependencies
k8-types = { version = "0.7.0", optional = true }

[dev-dependencies]

tokio = { version = "1.3.0", features = ["macros"] }
fluvio-future = { version = "0.4.0", features = ["fixture"] }
fluvio-stream-model = { path = ".", features = ["fixture"] }
async-std = { version = "1.8.0", default-features = false, features = [
    "attributes",
] }

[package.metadata.cargo-udeps.ignore]
development = [
    "fluvio-stream-model",
] # installed with `fixture` feature in tests
