[package]
name = "fluvio-protocol-derive"
description =  "Procedure macro to encode/decode fluvio protocol"
categories = ["encoding"]
version.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
proc-macro = true
doctest = false

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
tracing = { workspace = true }

[dependencies.syn]
version = "2.0.101"
features = ["full"]


