[package]
name = "fluvio-protocol-derive"
version = "0.5.2"
edition = "2021"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description =  "Procedure macro to encode/decode fluvio protocol"
repository = "https://github.com/infinyon/fluvio-protocol"
license = "Apache-2.0"
categories = ["encoding"]

[lib]
proc-macro = true
doctest = false

[dependencies]
proc-macro2 = "1.0.0"
quote = "1.0.0"
tracing = "0.1"

[dependencies.syn]
version = "2.0.22"
features = ["full"]


