[package]
name = "smdk"
version = "0.0.0"
edition = "2021"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "SmartModule Development Kit"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"
publish = false



[[bin]]
name = "smdk"
path = "src/main.rs"
doc = false


[dependencies]
tracing = "0.1.19"
clap = { version = "3.1.8", features = ["std", "derive"], default-features = false }
clap_complete = "3.1.1"
dirs = "4.0.0"
thiserror = "1.0.20"
anyhow = { version = "1.0.38" }

fluvio = { path = "../fluvio", default-features = false }
fluvio-protocol = { path = "../fluvio-protocol", features=["record","api"] }
fluvio-future = { version = "0.4.0", features = ["subscriber"]}
fluvio-smartengine = { path = "../fluvio-smartengine" }
fluvio-extension-common = { path = "../fluvio-extension-common", features = ["target"] }
fluvio-smartmodule = { path = "../fluvio-smartmodule",  default-features = false }
