[package]
name = "flv-sc-core"
edition = "2018"
version = "2.0.0"
authors = ["fluvio.io"]

[dependencies]
rand = "0.7.2"
log = "0.4.8"
toml = "0.5.5"
serde = { version ="1.0.103", features = ['derive'] }
futures = { version = "0.3.1" }
chashmap = "2.2.0"
base64 = "0.11.0"
regex = "1.3.1"
async-trait = "0.1.21"
async-lock = "1.1.2"
async-channel = "1.1.0"
event-listener = "2.2.0"
tokio = { version = "0.2.21", features = ["macros"] }
flv-util = { version = "0.2.0"}
flv-future-aio = { version = "2.3.0", features =["tls","unstable"] }
k8-metadata-client = { version = "1.0.1"}
k8-obj-metadata = { version = "1.0.0" }
flv-types = { path ="../types", version = "0.2.0"}
utils = { path = "../utils"}
kf-protocol = { version = "2.0.0" } 
kf-socket = {path = "../kf-socket"}
kf-service = { path = "../kf-service"}
internal-api = { path = "../internal-api"}
flv-metadata = { features = ["k8"],path = "../metadata"}
sc-api = { version = "2.0.0", path = "../sc-api",  package = "flv-api-sc"}

[dev-dependencies]
flv-future-aio = { version = "2.3.0", features=["fixture"]}
flv-util = { version = "0.2.0", features=["fixture"]}
