[package]
name = "fluvio-package-index"
version = "0.1.0"
authors = ["Infinyon Contributors <team@infiyon.com>"]
edition = "2018"

[lib]
name = "fluvio_index"
path = "src/lib.rs"

[dependencies]
tracing = "0.1.21"
thiserror = "1.0.21"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
semver = { version = "0.11.0", features = ["serde"] }
url = { version = "2.1.1", features = ["serde"] }
lazy_static = "1.4.0"
http-types = "2.6.0"
