[package]
name = "produce-stress"
version = "0.1.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2018"
publish = false

[dependencies]
fluvio = { path = "../../crates/fluvio" }
async-std = { version = "1.8.0", default-features = false, features = ["attributes"] }
