[package]
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio Test - TestCase derive macro"
edition = "2021"
license = "Apache-2.0"
name = "fluvio-test-case-derive"
publish = false
repository = "https://github.com/infinyon/fluvio"
version = "0.0.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = {version = "2.0", features = ["full"]}

[dev-dependencies]
trybuild = {git = "https://github.com/infinyon/trybuild", branch = "check_option"}
