[package]
name = "fluvio-controlplane-metadata"
edition = "2018"
version = "0.7.1"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio metadata"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"

[lib]
name = "fluvio_controlplane_metadata"
path = "src/lib.rs"

[features]
use_serde = ["serde"]
k8 = ["use_serde", "fluvio-stream-model/k8"]

[dependencies]
log = "0.4.8"
tracing = "0.1.19"
serde = { version = "1.0.0", features = ['derive'], optional = true }
async-trait = "0.1.21"

# Fluvio dependencies
fluvio-future = { version = "0.2.0" }
flv-util = { version = "0.5.0" }
fluvio-types = { version = "0.2.0", path = "../types" }
fluvio-stream-model = { path = "../stream-model", version = "0.5.0" }
fluvio-protocol = { path = "../protocol", version = "0.4.0" }
dataplane = { version = "0.4.0", path = "../dataplane-protocol", package = "fluvio-dataplane-protocol" }


[dev-dependencies]
fluvio-future = { version = "0.2.0", features = ["fixture"] }
