[package]
name = "flv-sc-k8"
edition = "2018"
version = "0.3.1"
authors = ["fluvio.io"]

[[bin]]
name = "sc-k8-server"
path = "src/main.rs"
doc = false

[dependencies]
rand = "0.7.2"
log = "0.4.8"
toml = "0.5.5"
structopt = "0.3.12"
serde = { version ="1.0.103", features = ['derive'] }
futures = { version = "0.3.4" }
k8-client = { version = "1.1.1"}
flv-types = { path ="../types", version = "0.2.0"}
utils = { path = "../utils"}
flv-future-aio = { version = "2.0.0", features = ["tls"] }
flv-util = { version = "0.1.0"}
k8-flv-metadata = { path = "../k8-metadata", version = "1.1.0"}
flv-sc-core = { path = "../sc-core"}
flv-metadata = { path = "../metadata"}
flv-tls-proxy = { path = "../proxy"}