[package]
name = "flv-sc-k8"
edition = "2018"
version = "0.1.0"
authors = ["fluvio.io"]

[[bin]]
name = "sc-k8-server"
path = "src/main.rs"
doc = false

[dependencies]
tracing = "0.1.19"
tracing-futures = "0.2.4"
rand = "0.7.2"
toml = "0.5.5"
structopt = "0.3.12"
serde = { version ="1.0.103", features = ['derive'] }
futures = { version = "0.3.4" }
async-trait = "0.1.21"
k8-client = { version = "1.1.1"}
flv-tls-proxy = "0.1.0"
flv-types = { path ="../types", version = "0.2.0"}
flv-future-aio = { version = "2.2.1", features = ["tls"] }
flv-util = { path = "../../../flv-util", version = "0.2.0" }
utils = { path = "../utils"}
flv-sc-core = { path = "../sc-core"}
flv-metadata-cluster = { features = ["k8"],path = "../metadata-cluster"}
