[package]
name = "fluvio-connector-derive"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
repository = "https://github.com/infinyon/fluvio"
description = "Fluvio SmartConnector procedural macro"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", default-features = false, features = ["full", "parsing", "proc-macro", "derive", "printing"] }
quote =  { workspace = true }
proc-macro2 = { workspace = true }