meta:
  version: 0.1.0
  name: my-json-test-connector
  type: json-test-source
  topic: test-topic
json:
  interval: 10  
  template: '{"template":"test"}'  
transforms:
  - uses: infinyon/jolt@0.1.0
    with:
      spec:
        - operation: default
          spec:
            data:
              source: "json-test-connector"
