[package]
name = "json-test-connector"
group = "fluvio"
version = "0.1.0"
apiVersion = "0.1.0"
fluvio = "0.10.0"
description = "Generate JSON generator"
license = "Apache-2.0"


[direction]
source = true

[deployment]
image = "infinyon/fluvio-connect-json-test-source:0.1.0"



[[params]]
name = "template"
description = "JSON template"
type = "string"

[[params]]
name = "interval"
description = "Interval in seconds"
type = "number"
