name: Publish Nightly Fluvio Docker Image

on: 
  schedule:
    - cron: '0 5 * * *' # run at 5AM UTC
jobs:
  publish:
    name: Publish Nightly
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Publish Fluvio Image
        run: |
          make fluvio_image_nightly