name: SmartModule Publish workflow

permissions: read-all

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      branch:
        type: string
        default: "main"
      rust-profile:
        type: string
        default: "release-lto"
      fail-fast:
        type: boolean
        default: true
      public:
        type: boolean
        default: true
      target_prod:
        type: boolean
        default: false
    secrets:
      ORG_HUB_SA_NAME:
        required: true
      ORG_HUB_SA_PASSWD_DEV:
        required: true
      ORG_HUB_SA_PASSWD_PROD:
        required: true
      ORG_CLOUD_URL_DEV:
        required: true

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
    steps:
      - name: Install Fluvio
        run: |
          curl -fsS https://packages.fluvio.io/v1/install.sh | bash
          echo "$HOME/.fluvio/bin" >> $GITHUB_PATH
      - name: Install Fluvio SMDK
        run: fluvio install smdk
      - name: Fluvio Login
        run: |
          fluvio cloud login --email ${{ secrets.ORG_HUB_SA_NAME }} \
          --password ${{ !inputs.target_prod && secrets.ORG_HUB_SA_PASSWD_DEV || secrets.ORG_HUB_SA_PASSWD_PROD }} \
          ${{ !inputs.target_prod && '--remote' || '' }} ${{ !inputs.target_prod && secrets.ORG_CLOUD_URL_DEV || '' }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-targets: "false"
          cache-on-failure: "true"
      - name: Build smartmodule
        run: smdk build
      - name: Publish
        run: |
          smdk ${{ inputs.public && '--public-yes' || '' }} \
            -p ${{ inputs.package-name }}
