name: SmartModule Publish workflow

permissions: read-all

on:
  workflow_call:
    inputs:
      fail-fast:
        type: boolean
        default: true
      public:
        type: boolean
        default: true
      target_prod:
        type: boolean
        default: false
      artifact-name:
        type: string
        required: true
      ipkg-file-name:
        type: string
        required: true

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
      CLOUD_LOGIN_PW:  ${{ !inputs.target_prod && secrets.ORG_HUB_SA_PASSWD_DEV || secrets.ORG_HUB_SA_PASSWD_PROD }}
    steps:
      - name: Setup Fluvio
        uses: infinyon/fluvio/.github/actions/setup-fluvio@master
      - name: Install Fluvio SMDK
        run: fluvio install smdk
      - name: Fluvio Login
        run: |
          fluvio cloud login --email "${{ secrets.ORG_HUB_SA_NAME }}" \
          --password "$CLOUD_LOGIN_PW" \
          ${{ !inputs.target_prod && '--remote' || '' }} ${{ !inputs.target_prod && secrets.ORG_CLOUD_URL_DEV || '' }}
      - uses: actions/download-artifact@v5
        id: download-file
        with:
          name: ${{ inputs.artifact-name }}
      - name: Publish
        run: |
          smdk publish ${{ inputs.public && '--public-yes' || '' }} \
          --push --ipkg ${{steps.download-file.outputs.download-path}}/${{inputs.ipkg-file-name}}
