[package]
name = "produce-key-value"
version = "0.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.8.0", default-features = false, features = ["attributes"] }
tracing-subscriber = "0.3.15"
anyhow = { workspace = true }

fluvio = { path = "../../crates/fluvio" }
