[package]
name = "produce-key-value"
version = "0.1.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluvio = { path = "../../crates/fluvio" }
async-std = { version = "1.8.0", default-features = false, features = ["attributes"] }
tracing-subscriber = "0.3.1"
